export const MORPH_TARGET: Record<MorphTarget, MorphTarget> = {
  viseme_sil: "viseme_sil",
  viseme_PP: "viseme_PP",
  viseme_FF: "viseme_FF",
  viseme_TH: "viseme_TH",
  viseme_DD: "viseme_DD",
  viseme_kk: "viseme_kk",
  viseme_CH: "viseme_CH",
  viseme_SS: "viseme_SS",
  viseme_nn: "viseme_nn",
  viseme_RR: "viseme_RR",
  viseme_aa: "viseme_aa",
  viseme_E: "viseme_E",
  viseme_I: "viseme_I",
  viseme_O: "viseme_O",
  viseme_U: "viseme_U",
  mouthOpen: "mouthOpen",
  mouthSmile: "mouthSmile",
  eyesClosed: "eyesClosed",
  eyesLookUp: "eyesLookUp",
  eyesLookDown: "eyesLookDown",
};
