import type { Metadata } from "next";

import { Toaster } from "@/shared/components";

import "../styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Toaster position="top-center" richColors />
    </html>
  );
}
