import type { Metadata } from "next";

import { Toaster } from "@/shared/components";
import { OverrideConsole } from "@/shared/lib";

import HeroUIProvider from "../providers/heroui";
import "../styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeroUIProvider>
          {children}
          <Toaster position="top-center" richColors />
        </HeroUIProvider>
        {process.env.NODE_ENV === "development" && <OverrideConsole />}
      </body>
    </html>
  );
}
