export const WEBSOCKET_BASE_URL = process.env.NEXT_PUBLIC_WEBSOCKET_BASE_URL;

export const TURN_SERVER_URL = process.env.NEXT_PUBLIC_TURN_SERVER_URL;
export const TURN_SERVER_USERNAME =
  process.env.NEXT_PUBLIC_TURN_SERVER_USERNAME;
export const TURN_SERVER_CREDENTIAL =
  process.env.NEXT_PUBLIC_TURN_SERVER_CREDENTIAL;
